service: site-creation-v2
frameworkVersion: '3'

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs14.x
  stage: staging
  region: ap-southeast-1
  environment:
    GITHUB_ACCESS_TOKEN: ${env:GITHUB_ACCESS_TOKEN}
    NODE_ENV: ${env:NODE_ENV}
    CMS_URL: ${env:CMS_URL}
    CMS_SYSTEM_SECRET: ${env:CMS_SYSTEM_SECRET}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'ses:SendRawEmail'
          Resource:
            '*'
        - Effect: 'Allow'
          Action:
            - 'amplify:CreateApp'
            - 'amplify:CreateBranch'
          Resource: arn:aws:amplify:${aws:region}:${aws:accountId}:apps/*

functions:
  sites:
    handler: dist/serverless.handler
    url:
      cors: true
    timeout: 30
    environment:
      FORM_CREATE_KEY: ${env:FORM_CREATE_KEY}

useDotenv: true